### POST Creates a new Patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Samwel Mwawasi",
  "address": "Kamiti Road 1231",
  "dateOfBirth": "1995-09-09",
  "registeredDate": "2025-05-22"
}
###